[project]
name = "hamsa-android"
version = "1.0.0"
description = "HAMSA weather application"
requires-python = ">=3.13,<3.14"
dependencies = [
    "flet",
    "jdatetime",
    "flet-geolocator",
    "flet-webview"
]

[tool.flet]
product = "HAMSA"
org = "com.hamsa"

[tool.flet.android]
permissions = [
    "location"
]
