[project]
name = "hamsa-android"
version = "1.0.0"
description = "HAMSA weather application"
requires-python = ">=3.12,<3.13"

dependencies = [
    "flet==1.0.0",
    "aiohttp",
    "jdatetime",
    "flet-geolocator",
    "flet-webview",
    "pandas",
    "numpy",
    "scikit-learn"
]

[tool.flet]
product = "همسا"
org = "com.hamsa"
icon_background = "#ffffff"
icon = assets/icon.png

[tool.flet.android]
permissions = [
    "location"
]
extract_packages = [
    "sklearn"
]
